// ==========================================
// Auto Slay the Spire — 卡牌 / 遺物 / 藥水資料
// 數值參考原作 wiki（部分機制簡化以利自動演示）
// t: a=攻擊 s=技能 p=能力 | r: 0起始 1普通 2罕見 3稀有
// tg: e=單體 all=全體 self=自身
// ==========================================

const CHARS = {
  ironclad: { name: '鐵甲戰士', en: 'Ironclad', hp: 80, color: '#8B2E2E', body: '#A83232',
              relic: 'burning_blood', deck: ['strike','strike','strike','strike','strike','defend','defend','defend','defend','bash'] },
  silent:   { name: '靜默獵手', en: 'Silent', hp: 70, color: '#2E6B3A', body: '#3D8B4F',
              relic: 'ring_snake', deck: ['strike','strike','strike','strike','strike','defend','defend','defend','defend','defend','neutralize','survivor'] },
  defect:   { name: '故障機器人', en: 'Defect', hp: 75, color: '#2E5A8B', body: '#3A72B0',
              relic: 'cracked_core', deck: ['strike','strike','strike','strike','defend','defend','defend','defend','zap','dualcast'] },
  watcher:  { name: '觀者', en: 'Watcher', hp: 72, color: '#6B2E8B', body: '#8B3AB0',
              relic: 'pure_water', deck: ['strike','strike','strike','strike','defend','defend','defend','defend','eruption','vigilance','pray'] },
};

// ── 卡牌 ──────────────────────────────────────────────
// fx 鍵：dmg hits aoe block vuln weak str dex draw energy heal selfDmg loseHP
//        poison poisonAll thorns metallicize exhaust(打出後消耗) xCost
//        blockAsDmg strMult dmgPerStrike shiv discard channel(orb) focus
//        stance(wrath/calm) mantra intangible 及各能力旗標

const CARDS = {
  // ═══ 通用起始 ═══
  strike:   { n:'打擊', en:'Strike', c:1, t:'a', r:0, tg:'e', fx:{dmg:6} },
  defend:   { n:'防禦', en:'Defend', c:1, t:'s', r:0, tg:'self', fx:{block:5} },

  // ═══ 鐵甲戰士（紅）═══
  bash:            { n:'痛擊', en:'Bash', ch:'ironclad', c:2, t:'a', r:0, tg:'e', fx:{dmg:8, vuln:2} },
  anger:           { n:'憤怒', en:'Anger', ch:'ironclad', c:0, t:'a', r:1, tg:'e', fx:{dmg:6} },
  armaments:       { n:'武裝', en:'Armaments', ch:'ironclad', c:1, t:'s', r:1, tg:'self', fx:{block:5, upgradeRandom:1} },
  body_slam:       { n:'鐵山靠', en:'Body Slam', ch:'ironclad', c:1, t:'a', r:1, tg:'e', fx:{blockAsDmg:1} },
  clash:           { n:'衝突', en:'Clash', ch:'ironclad', c:0, t:'a', r:1, tg:'e', fx:{dmg:14, needAllAttacks:1} },
  cleave:          { n:'順劈斬', en:'Cleave', ch:'ironclad', c:1, t:'a', r:1, tg:'all', fx:{dmg:8, aoe:1} },
  clothesline:     { n:'金勾臂', en:'Clothesline', ch:'ironclad', c:2, t:'a', r:1, tg:'e', fx:{dmg:12, weak:2} },
  flex:            { n:'屈伸', en:'Flex', ch:'ironclad', c:0, t:'s', r:1, tg:'self', fx:{str:2, strDownEnd:2} },
  headbutt:        { n:'頭錘', en:'Headbutt', ch:'ironclad', c:1, t:'a', r:1, tg:'e', fx:{dmg:9} },
  heavy_blade:     { n:'重刃', en:'Heavy Blade', ch:'ironclad', c:2, t:'a', r:1, tg:'e', fx:{dmg:14, strMult:3} },
  iron_wave:       { n:'鐵斬波', en:'Iron Wave', ch:'ironclad', c:1, t:'a', r:1, tg:'e', fx:{dmg:5, block:5} },
  perfected_strike:{ n:'完美打擊', en:'Perfected Strike', ch:'ironclad', c:2, t:'a', r:1, tg:'e', fx:{dmg:6, dmgPerStrike:2} },
  pommel_strike:   { n:'劍柄打擊', en:'Pommel Strike', ch:'ironclad', c:1, t:'a', r:1, tg:'e', fx:{dmg:9, draw:1} },
  shrug_it_off:    { n:'聳肩置之', en:'Shrug It Off', ch:'ironclad', c:1, t:'s', r:1, tg:'self', fx:{block:8, draw:1} },
  sword_boomerang: { n:'飛劍迴旋鏢', en:'Sword Boomerang', ch:'ironclad', c:1, t:'a', r:1, tg:'e', fx:{dmg:3, hits:3, randomTarget:1} },
  thunderclap:     { n:'雷霆一擊', en:'Thunderclap', ch:'ironclad', c:1, t:'a', r:1, tg:'all', fx:{dmg:4, aoe:1, vuln:1} },
  true_grit:       { n:'堅毅不屈', en:'True Grit', ch:'ironclad', c:1, t:'s', r:1, tg:'self', fx:{block:7} },
  twin_strike:     { n:'雙重打擊', en:'Twin Strike', ch:'ironclad', c:1, t:'a', r:1, tg:'e', fx:{dmg:5, hits:2} },
  wild_strike:     { n:'狂野打擊', en:'Wild Strike', ch:'ironclad', c:1, t:'a', r:1, tg:'e', fx:{dmg:12} },
  battle_trance:   { n:'戰鬥專注', en:'Battle Trance', ch:'ironclad', c:0, t:'s', r:2, tg:'self', fx:{draw:3} },
  blood_for_blood: { n:'血債血償', en:'Blood for Blood', ch:'ironclad', c:2, t:'a', r:2, tg:'e', fx:{dmg:18} },
  bloodletting:    { n:'放血', en:'Bloodletting', ch:'ironclad', c:0, t:'s', r:2, tg:'self', fx:{loseHP:3, energy:2} },
  burning_pact:    { n:'燃燒契約', en:'Burning Pact', ch:'ironclad', c:1, t:'s', r:2, tg:'self', fx:{draw:2} },
  carnage:         { n:'殺戮', en:'Carnage', ch:'ironclad', c:2, t:'a', r:2, tg:'e', fx:{dmg:20, ethereal:1} },
  combust:         { n:'自燃', en:'Combust', ch:'ironclad', c:1, t:'p', r:2, tg:'self', fx:{combust:5} },
  dark_embrace:    { n:'黑暗擁抱', en:'Dark Embrace', ch:'ironclad', c:2, t:'p', r:2, tg:'self', fx:{darkEmbrace:1} },
  disarm:          { n:'繳械', en:'Disarm', ch:'ironclad', c:1, t:'s', r:2, tg:'e', fx:{strDown:2, exhaust:1} },
  dropkick:        { n:'飛踢', en:'Dropkick', ch:'ironclad', c:1, t:'a', r:2, tg:'e', fx:{dmg:5, ifVulnEnergy:1} },
  entrench:        { n:'壕溝掘進', en:'Entrench', ch:'ironclad', c:2, t:'s', r:2, tg:'self', fx:{doubleBlock:1} },
  evolve:          { n:'進化', en:'Evolve', ch:'ironclad', c:1, t:'p', r:2, tg:'self', fx:{evolve:1} },
  feel_no_pain:    { n:'無痛', en:'Feel No Pain', ch:'ironclad', c:1, t:'p', r:2, tg:'self', fx:{feelNoPain:3} },
  flame_barrier:   { n:'火焰屏障', en:'Flame Barrier', ch:'ironclad', c:2, t:'s', r:2, tg:'self', fx:{block:12, thorns:4} },
  ghostly_armor:   { n:'幽靈鎧甲', en:'Ghostly Armor', ch:'ironclad', c:1, t:'s', r:2, tg:'self', fx:{block:10, ethereal:1} },
  hemokinesis:     { n:'血氣操控', en:'Hemokinesis', ch:'ironclad', c:1, t:'a', r:2, tg:'e', fx:{dmg:15, loseHP:2} },
  inflame:         { n:'怒火中燒', en:'Inflame', ch:'ironclad', c:1, t:'p', r:2, tg:'self', fx:{str:2} },
  intimidate:      { n:'威嚇', en:'Intimidate', ch:'ironclad', c:0, t:'s', r:2, tg:'all', fx:{weakAll:1, exhaust:1} },
  metallicize:     { n:'金屬化', en:'Metallicize', ch:'ironclad', c:1, t:'p', r:2, tg:'self', fx:{metallicize:3} },
  pummel:          { n:'連續猛擊', en:'Pummel', ch:'ironclad', c:1, t:'a', r:2, tg:'e', fx:{dmg:2, hits:4, exhaust:1} },
  rampage:         { n:'暴走', en:'Rampage', ch:'ironclad', c:1, t:'a', r:2, tg:'e', fx:{dmg:8, rampage:5} },
  seeing_red:      { n:'眼紅', en:'Seeing Red', ch:'ironclad', c:1, t:'s', r:2, tg:'self', fx:{energy:2, exhaust:1} },
  sentinel:        { n:'哨衛', en:'Sentinel', ch:'ironclad', c:1, t:'s', r:2, tg:'self', fx:{block:5} },
  shockwave:       { n:'衝擊波', en:'Shockwave', ch:'ironclad', c:2, t:'s', r:2, tg:'all', fx:{weakAll:3, vulnAll:3, exhaust:1} },
  uppercut:        { n:'上勾拳', en:'Uppercut', ch:'ironclad', c:2, t:'a', r:2, tg:'e', fx:{dmg:13, weak:1, vuln:1} },
  whirlwind:       { n:'旋風斬', en:'Whirlwind', ch:'ironclad', c:-1, t:'a', r:2, tg:'all', fx:{dmg:5, aoe:1, xCost:1} },
  barricade:       { n:'壁壘', en:'Barricade', ch:'ironclad', c:3, t:'p', r:3, tg:'self', fx:{barricade:1} },
  bludgeon:        { n:'重槌', en:'Bludgeon', ch:'ironclad', c:3, t:'a', r:3, tg:'e', fx:{dmg:32} },
  demon_form:      { n:'惡魔化', en:'Demon Form', ch:'ironclad', c:3, t:'p', r:3, tg:'self', fx:{demonForm:2} },
  double_tap:      { n:'二連擊', en:'Double Tap', ch:'ironclad', c:1, t:'s', r:3, tg:'self', fx:{doubleTap:1} },
  feed:            { n:'吞噬', en:'Feed', ch:'ironclad', c:1, t:'a', r:3, tg:'e', fx:{dmg:10, feedMaxHP:3, exhaust:1} },
  immolate:        { n:'獻祭', en:'Immolate', ch:'ironclad', c:2, t:'a', r:3, tg:'all', fx:{dmg:21, aoe:1} },
  impervious:      { n:'金剛不壞', en:'Impervious', ch:'ironclad', c:2, t:'s', r:3, tg:'self', fx:{block:30, exhaust:1} },
  juggernaut:      { n:'主宰', en:'Juggernaut', ch:'ironclad', c:2, t:'p', r:3, tg:'self', fx:{juggernaut:5} },
  limit_break:     { n:'突破極限', en:'Limit Break', ch:'ironclad', c:1, t:'s', r:3, tg:'self', fx:{doubleStr:1, exhaust:1} },
  offering:        { n:'奉獻', en:'Offering', ch:'ironclad', c:0, t:'s', r:3, tg:'self', fx:{loseHP:6, energy:2, draw:3, exhaust:1} },
  reaper:          { n:'死神鐮刀', en:'Reaper', ch:'ironclad', c:2, t:'a', r:3, tg:'all', fx:{dmg:4, aoe:1, reap:1, exhaust:1} },

  // ═══ 靜默獵手（綠）═══
  neutralize:      { n:'中和', en:'Neutralize', ch:'silent', c:0, t:'a', r:0, tg:'e', fx:{dmg:3, weak:1} },
  survivor:        { n:'倖存者', en:'Survivor', ch:'silent', c:1, t:'s', r:0, tg:'self', fx:{block:8, discard:1} },
  acrobatics:      { n:'雜技', en:'Acrobatics', ch:'silent', c:1, t:'s', r:1, tg:'self', fx:{draw:3, discard:1} },
  backflip:        { n:'後空翻', en:'Backflip', ch:'silent', c:1, t:'s', r:1, tg:'self', fx:{block:5, draw:2} },
  bane:            { n:'毒殺', en:'Bane', ch:'silent', c:1, t:'a', r:1, tg:'e', fx:{dmg:7, dmgIfPoisonx2:1} },
  blade_dance:     { n:'劍刃之舞', en:'Blade Dance', ch:'silent', c:1, t:'s', r:1, tg:'self', fx:{shiv:3} },
  cloak_dagger:    { n:'披風與匕首', en:'Cloak and Dagger', ch:'silent', c:1, t:'s', r:1, tg:'self', fx:{block:6, shiv:1} },
  dagger_spray:    { n:'匕首噴射', en:'Dagger Spray', ch:'silent', c:1, t:'a', r:1, tg:'all', fx:{dmg:4, hits:2, aoe:1} },
  dagger_throw:    { n:'飛刀', en:'Dagger Throw', ch:'silent', c:1, t:'a', r:1, tg:'e', fx:{dmg:9, draw:1, discard:1} },
  deadly_poison:   { n:'致命毒藥', en:'Deadly Poison', ch:'silent', c:1, t:'s', r:1, tg:'e', fx:{poison:5} },
  deflect:         { n:'偏斜', en:'Deflect', ch:'silent', c:0, t:'s', r:1, tg:'self', fx:{block:4} },
  dodge_roll:      { n:'翻滾閃避', en:'Dodge and Roll', ch:'silent', c:1, t:'s', r:1, tg:'self', fx:{block:4, blockNext:4} },
  flying_knee:     { n:'飛膝踢', en:'Flying Knee', ch:'silent', c:1, t:'a', r:1, tg:'e', fx:{dmg:8, energyNext:1} },
  outmaneuver:     { n:'巧妙規避', en:'Outmaneuver', ch:'silent', c:1, t:'s', r:1, tg:'self', fx:{energyNext:2} },
  piercing_wail:   { n:'刺耳哀嚎', en:'Piercing Wail', ch:'silent', c:1, t:'s', r:1, tg:'all', fx:{strDownAll:6, exhaust:1} },
  poisoned_stab:   { n:'淬毒刺擊', en:'Poisoned Stab', ch:'silent', c:1, t:'a', r:1, tg:'e', fx:{dmg:6, poison:3} },
  prepared:        { n:'蓄勢待發', en:'Prepared', ch:'silent', c:0, t:'s', r:1, tg:'self', fx:{draw:1, discard:1} },
  quick_slash:     { n:'快速斬擊', en:'Quick Slash', ch:'silent', c:1, t:'a', r:1, tg:'e', fx:{dmg:8, draw:1} },
  slice:           { n:'切割', en:'Slice', ch:'silent', c:0, t:'a', r:1, tg:'e', fx:{dmg:6} },
  sucker_punch:    { n:'不意突擊', en:'Sucker Punch', ch:'silent', c:1, t:'a', r:1, tg:'e', fx:{dmg:7, weak:1} },
  accuracy:        { n:'精準', en:'Accuracy', ch:'silent', c:1, t:'p', r:2, tg:'self', fx:{accuracy:4} },
  all_out_attack:  { n:'傾力攻擊', en:'All-Out Attack', ch:'silent', c:1, t:'a', r:2, tg:'all', fx:{dmg:10, aoe:1, discardRandom:1} },
  backstab:        { n:'背刺', en:'Backstab', ch:'silent', c:0, t:'a', r:2, tg:'e', fx:{dmg:11, exhaust:1} },
  blur:            { n:'朦朧', en:'Blur', ch:'silent', c:1, t:'s', r:2, tg:'self', fx:{block:5, blockKeep:1} },
  calculated_gamble:{ n:'精算賭博', en:'Calculated Gamble', ch:'silent', c:0, t:'s', r:2, tg:'self', fx:{gamble:1, exhaust:1} },
  caltrops:        { n:'鐵蒺藜', en:'Caltrops', ch:'silent', c:1, t:'p', r:2, tg:'self', fx:{thornsPerm:3} },
  catalyst:        { n:'催化劑', en:'Catalyst', ch:'silent', c:1, t:'s', r:2, tg:'e', fx:{poisonDouble:1, exhaust:1} },
  choke:           { n:'扼喉', en:'Choke', ch:'silent', c:2, t:'a', r:2, tg:'e', fx:{dmg:12, choke:3} },
  crippling_cloud: { n:'致殘雲霧', en:'Crippling Cloud', ch:'silent', c:2, t:'s', r:2, tg:'all', fx:{poisonAll:4, weakAll:2, exhaust:1} },
  dash:            { n:'衝刺', en:'Dash', ch:'silent', c:2, t:'a', r:2, tg:'e', fx:{dmg:10, block:10} },
  endless_agony:   { n:'無盡苦悶', en:'Endless Agony', ch:'silent', c:0, t:'a', r:2, tg:'e', fx:{dmg:4, exhaust:1} },
  escape_plan:     { n:'逃跑計畫', en:'Escape Plan', ch:'silent', c:0, t:'s', r:2, tg:'self', fx:{draw:1, blockIfSkill:3} },
  eviscerate:      { n:'剜剔', en:'Eviscerate', ch:'silent', c:3, t:'a', r:2, tg:'e', fx:{dmg:7, hits:3} },
  expertise:       { n:'專業技能', en:'Expertise', ch:'silent', c:1, t:'s', r:2, tg:'self', fx:{drawTo:6} },
  finisher:        { n:'終結技', en:'Finisher', ch:'silent', c:1, t:'a', r:2, tg:'e', fx:{finisher:6} },
  flechettes:      { n:'飛鏢齊射', en:'Flechettes', ch:'silent', c:1, t:'a', r:2, tg:'e', fx:{flechettes:4} },
  footwork:        { n:'步法', en:'Footwork', ch:'silent', c:1, t:'p', r:2, tg:'self', fx:{dex:2} },
  heel_hook:       { n:'腳跟勾踢', en:'Heel Hook', ch:'silent', c:1, t:'a', r:2, tg:'e', fx:{dmg:5, ifWeakEnergy:1} },
  infinite_blades: { n:'無限刀刃', en:'Infinite Blades', ch:'silent', c:1, t:'p', r:2, tg:'self', fx:{infiniteBlades:1} },
  leg_sweep:       { n:'掃堂腿', en:'Leg Sweep', ch:'silent', c:2, t:'s', r:2, tg:'e', fx:{weak:2, block:11} },
  masterful_stab:  { n:'嫻熟刺擊', en:'Masterful Stab', ch:'silent', c:0, t:'a', r:2, tg:'e', fx:{dmg:12} },
  noxious_fumes:   { n:'毒霧', en:'Noxious Fumes', ch:'silent', c:1, t:'p', r:2, tg:'self', fx:{noxiousFumes:2} },
  predator:        { n:'捕食者', en:'Predator', ch:'silent', c:2, t:'a', r:2, tg:'e', fx:{dmg:15, drawNext:2} },
  riddle_holes:    { n:'千瘡百孔', en:'Riddle with Holes', ch:'silent', c:2, t:'a', r:2, tg:'e', fx:{dmg:3, hits:5} },
  skewer:          { n:'串刺', en:'Skewer', ch:'silent', c:-1, t:'a', r:2, tg:'e', fx:{dmg:7, xCost:1} },
  terror:          { n:'驚駭', en:'Terror', ch:'silent', c:1, t:'s', r:2, tg:'e', fx:{vuln:99, exhaust:1} },
  a_thousand_cuts: { n:'千刀萬剮', en:'A Thousand Cuts', ch:'silent', c:2, t:'p', r:3, tg:'self', fx:{thousandCuts:1} },
  adrenaline:      { n:'腎上腺素', en:'Adrenaline', ch:'silent', c:0, t:'s', r:3, tg:'self', fx:{energy:1, draw:2, exhaust:1} },
  after_image:     { n:'殘像', en:'After Image', ch:'silent', c:1, t:'p', r:3, tg:'self', fx:{afterImage:1} },
  bullet_time:     { n:'子彈時間', en:'Bullet Time', ch:'silent', c:3, t:'s', r:3, tg:'self', fx:{bulletTime:1} },
  die_die_die:     { n:'死死死', en:'Die Die Die', ch:'silent', c:1, t:'a', r:3, tg:'all', fx:{dmg:13, aoe:1, exhaust:1} },
  envenom:         { n:'淬毒', en:'Envenom', ch:'silent', c:2, t:'p', r:3, tg:'self', fx:{envenom:1} },
  glass_knife:     { n:'玻璃刀', en:'Glass Knife', ch:'silent', c:1, t:'a', r:3, tg:'e', fx:{dmg:8, hits:2, glassKnife:1} },
  grand_finale:    { n:'終幕', en:'Grand Finale', ch:'silent', c:0, t:'a', r:3, tg:'all', fx:{dmg:50, aoe:1, needEmptyDraw:1} },
  unload:          { n:'傾瀉', en:'Unload', ch:'silent', c:1, t:'a', r:3, tg:'e', fx:{dmg:14, discardNonAttack:1} },
  wraith_form:     { n:'鬼魅之形', en:'Wraith Form', ch:'silent', c:3, t:'p', r:3, tg:'self', fx:{intangible:2, exhaust:1} },

  // ═══ 故障機器人（藍）═══
  zap:             { n:'電擊', en:'Zap', ch:'defect', c:1, t:'s', r:0, tg:'self', fx:{channel:'lightning'} },
  dualcast:        { n:'雙重施法', en:'Dualcast', ch:'defect', c:1, t:'s', r:0, tg:'self', fx:{evokeX:2} },
  ball_lightning:  { n:'球狀閃電', en:'Ball Lightning', ch:'defect', c:1, t:'a', r:1, tg:'e', fx:{dmg:7, channel:'lightning'} },
  barrage:         { n:'彈幕', en:'Barrage', ch:'defect', c:1, t:'a', r:1, tg:'e', fx:{dmgPerOrb:4} },
  beam_cell:       { n:'光束單元', en:'Beam Cell', ch:'defect', c:0, t:'a', r:1, tg:'e', fx:{dmg:3, vuln:1} },
  charge_battery:  { n:'蓄電', en:'Charge Battery', ch:'defect', c:1, t:'s', r:1, tg:'self', fx:{block:7, energyNext:1} },
  claw:            { n:'爪擊', en:'Claw', ch:'defect', c:0, t:'a', r:1, tg:'e', fx:{dmg:3, clawGrow:2} },
  cold_snap:       { n:'寒潮', en:'Cold Snap', ch:'defect', c:1, t:'a', r:1, tg:'e', fx:{dmg:6, channel:'frost'} },
  compile_driver:  { n:'編譯驅動', en:'Compile Driver', ch:'defect', c:1, t:'a', r:1, tg:'e', fx:{dmg:7, drawPerOrbType:1} },
  coolheaded:      { n:'冷靜思考', en:'Coolheaded', ch:'defect', c:1, t:'s', r:1, tg:'self', fx:{channel:'frost', draw:1} },
  go_for_eyes:     { n:'直取要害', en:'Go for the Eyes', ch:'defect', c:0, t:'a', r:1, tg:'e', fx:{dmg:3, weak:1} },
  hologram:        { n:'全息影像', en:'Hologram', ch:'defect', c:1, t:'s', r:1, tg:'self', fx:{block:3, retrieve:1} },
  leap:            { n:'躍擊', en:'Leap', ch:'defect', c:1, t:'s', r:1, tg:'self', fx:{block:9} },
  rebound:         { n:'反彈', en:'Rebound', ch:'defect', c:1, t:'a', r:1, tg:'e', fx:{dmg:9} },
  stack:           { n:'堆疊', en:'Stack', ch:'defect', c:1, t:'s', r:1, tg:'self', fx:{blockPerDiscard:1} },
  steam_barrier:   { n:'蒸汽屏障', en:'Steam Barrier', ch:'defect', c:0, t:'s', r:1, tg:'self', fx:{block:6, steamShrink:1} },
  streamline:      { n:'流線', en:'Streamline', ch:'defect', c:2, t:'a', r:1, tg:'e', fx:{dmg:15, costDown:1} },
  sweeping_beam:   { n:'掃射光束', en:'Sweeping Beam', ch:'defect', c:1, t:'a', r:1, tg:'all', fx:{dmg:6, aoe:1, draw:1} },
  turbo:           { n:'渦輪增壓', en:'TURBO', ch:'defect', c:0, t:'s', r:1, tg:'self', fx:{energy:2} },
  auto_shields:    { n:'自動護盾', en:'Auto-Shields', ch:'defect', c:1, t:'s', r:2, tg:'self', fx:{autoShields:11} },
  blizzard:        { n:'暴風雪', en:'Blizzard', ch:'defect', c:1, t:'a', r:2, tg:'all', fx:{blizzard:2, aoe:1} },
  bullseye:        { n:'紅心', en:'Bullseye', ch:'defect', c:1, t:'a', r:2, tg:'e', fx:{dmg:8, lockOn:2} },
  capacitor:       { n:'電容器', en:'Capacitor', ch:'defect', c:1, t:'p', r:2, tg:'self', fx:{orbSlots:2} },
  chill:           { n:'冷卻', en:'Chill', ch:'defect', c:0, t:'s', r:2, tg:'self', fx:{chillAll:1, exhaust:1} },
  consume:         { n:'消耗', en:'Consume', ch:'defect', c:2, t:'s', r:2, tg:'self', fx:{focus:2, loseSlot:1} },
  darkness:        { n:'黑暗', en:'Darkness', ch:'defect', c:1, t:'s', r:2, tg:'self', fx:{channel:'dark'} },
  defragment:      { n:'磁碟重組', en:'Defragment', ch:'defect', c:1, t:'p', r:2, tg:'self', fx:{focus:1} },
  doom_and_gloom:  { n:'末日陰霾', en:'Doom and Gloom', ch:'defect', c:2, t:'a', r:2, tg:'all', fx:{dmg:10, aoe:1, channel:'dark'} },
  double_energy:   { n:'能量倍增', en:'Double Energy', ch:'defect', c:1, t:'s', r:2, tg:'self', fx:{doubleEnergy:1, exhaust:1} },
  equilibrium:     { n:'均衡', en:'Equilibrium', ch:'defect', c:2, t:'s', r:2, tg:'self', fx:{block:13} },
  force_field:     { n:'力場', en:'Force Field', ch:'defect', c:4, t:'s', r:2, tg:'self', fx:{block:12, ffCostDown:1} },
  ftl:             { n:'超光速', en:'FTL', ch:'defect', c:0, t:'a', r:2, tg:'e', fx:{dmg:5, drawIfFew:1} },
  glacier:         { n:'冰川', en:'Glacier', ch:'defect', c:2, t:'s', r:2, tg:'self', fx:{block:7, channel:'frost', channel2:'frost'} },
  heatsinks:       { n:'散熱片', en:'Heatsinks', ch:'defect', c:1, t:'p', r:2, tg:'self', fx:{heatsinks:1} },
  hello_world:     { n:'你好世界', en:'Hello World', ch:'defect', c:1, t:'p', r:2, tg:'self', fx:{helloWorld:1} },
  loop:            { n:'迴圈', en:'Loop', ch:'defect', c:1, t:'p', r:2, tg:'self', fx:{loop:1} },
  melter:          { n:'熔化器', en:'Melter', ch:'defect', c:1, t:'a', r:2, tg:'e', fx:{dmg:10, removeBlock:1} },
  overclock:       { n:'超頻', en:'Overclock', ch:'defect', c:0, t:'s', r:2, tg:'self', fx:{draw:2} },
  recycle:         { n:'回收', en:'Recycle', ch:'defect', c:1, t:'s', r:2, tg:'self', fx:{recycle:1} },
  reinforced_body: { n:'強化機體', en:'Reinforced Body', ch:'defect', c:-1, t:'s', r:2, tg:'self', fx:{block:7, xCost:1} },
  rip_and_tear:    { n:'撕裂', en:'Rip and Tear', ch:'defect', c:1, t:'a', r:2, tg:'e', fx:{dmg:7, hits:2, randomTarget:1} },
  self_repair:     { n:'自我修復', en:'Self Repair', ch:'defect', c:1, t:'p', r:2, tg:'self', fx:{selfRepair:7} },
  skim:            { n:'略讀', en:'Skim', ch:'defect', c:1, t:'s', r:2, tg:'self', fx:{draw:3} },
  static_discharge:{ n:'靜電放電', en:'Static Discharge', ch:'defect', c:1, t:'p', r:2, tg:'self', fx:{staticDischarge:1} },
  storm:           { n:'風暴', en:'Storm', ch:'defect', c:1, t:'p', r:2, tg:'self', fx:{storm:1} },
  sunder:          { n:'裂解', en:'Sunder', ch:'defect', c:3, t:'a', r:2, tg:'e', fx:{dmg:24, refundIfKill:3} },
  tempest:         { n:'風暴驟雨', en:'Tempest', ch:'defect', c:-1, t:'s', r:2, tg:'self', fx:{channelXLightning:1, xCost:1, exhaust:1} },
  amplify:         { n:'增幅', en:'Amplify', ch:'defect', c:1, t:'s', r:3, tg:'self', fx:{amplify:1} },
  biased_cognition:{ n:'認知偏差', en:'Biased Cognition', ch:'defect', c:1, t:'p', r:3, tg:'self', fx:{focus:4, biasDecay:1} },
  buffer:          { n:'緩衝', en:'Buffer', ch:'defect', c:2, t:'s', r:3, tg:'self', fx:{buffer:1} },
  core_surge:      { n:'核心湧動', en:'Core Surge', ch:'defect', c:1, t:'a', r:3, tg:'e', fx:{dmg:11, artifact:1, exhaust:1} },
  echo_form:       { n:'回音形態', en:'Echo Form', ch:'defect', c:3, t:'p', r:3, tg:'self', fx:{echoForm:1} },
  electrodynamics: { n:'電動力學', en:'Electrodynamics', ch:'defect', c:2, t:'p', r:3, tg:'self', fx:{electrodynamics:1, channel:'lightning', channel2:'lightning'} },
  hyperbeam:       { n:'超級光束', en:'Hyperbeam', ch:'defect', c:2, t:'a', r:3, tg:'all', fx:{dmg:26, aoe:1, focusDown:3} },
  meteor_strike:   { n:'隕石打擊', en:'Meteor Strike', ch:'defect', c:5, t:'a', r:3, tg:'e', fx:{dmg:24, channel:'plasma', channel2:'plasma'} },
  multi_cast:      { n:'多重施法', en:'Multi-Cast', ch:'defect', c:-1, t:'s', r:3, tg:'self', fx:{evokeXTimes:1, xCost:1} },
  seek:            { n:'探尋', en:'Seek', ch:'defect', c:0, t:'s', r:3, tg:'self', fx:{seek:1, exhaust:1} },
  thunder_strike:  { n:'雷霆萬鈞', en:'Thunder Strike', ch:'defect', c:3, t:'a', r:3, tg:'all', fx:{thunderStrike:7} },

  // ═══ 觀者（紫）═══
  eruption:        { n:'爆發', en:'Eruption', ch:'watcher', c:2, t:'a', r:0, tg:'e', fx:{dmg:9, stance:'wrath'} },
  vigilance:       { n:'警戒', en:'Vigilance', ch:'watcher', c:2, t:'s', r:0, tg:'self', fx:{block:8, stance:'calm'} },
  bowling_bash:    { n:'保齡連擊', en:'Bowling Bash', ch:'watcher', c:1, t:'a', r:1, tg:'e', fx:{dmgPerEnemy:7} },
  consecrate:      { n:'奉獻', en:'Consecrate', ch:'watcher', c:0, t:'a', r:1, tg:'all', fx:{dmg:5, aoe:1} },
  crescendo:       { n:'漸強', en:'Crescendo', ch:'watcher', c:1, t:'s', r:1, tg:'self', fx:{stance:'wrath', exhaust:1} },
  crush_joints:    { n:'碎骨', en:'Crush Joints', ch:'watcher', c:1, t:'a', r:1, tg:'e', fx:{dmg:8, vulnIfSkillLast:1} },
  cut_through_fate:{ n:'斬斷命運', en:'Cut Through Fate', ch:'watcher', c:1, t:'a', r:1, tg:'e', fx:{dmg:7, draw:1} },
  empty_body:      { n:'空靈之身', en:'Empty Body', ch:'watcher', c:1, t:'s', r:1, tg:'self', fx:{block:7, exitStance:1} },
  empty_fist:      { n:'空靈之拳', en:'Empty Fist', ch:'watcher', c:1, t:'a', r:1, tg:'e', fx:{dmg:9, exitStance:1} },
  evaluate:        { n:'沉思', en:'Evaluate', ch:'watcher', c:1, t:'s', r:1, tg:'self', fx:{block:6} },
  flurry_of_blows: { n:'亂拳', en:'Flurry of Blows', ch:'watcher', c:0, t:'a', r:1, tg:'e', fx:{dmg:4} },
  flying_sleeves:  { n:'飛袖', en:'Flying Sleeves', ch:'watcher', c:1, t:'a', r:1, tg:'e', fx:{dmg:4, hits:2} },
  follow_up:       { n:'追擊', en:'Follow-Up', ch:'watcher', c:1, t:'a', r:1, tg:'e', fx:{dmg:7, refundIfAttackLast:1} },
  halt:            { n:'停頓', en:'Halt', ch:'watcher', c:0, t:'s', r:1, tg:'self', fx:{block:3, blockIfWrath:9} },
  just_lucky:      { n:'運氣不錯', en:'Just Lucky', ch:'watcher', c:0, t:'a', r:1, tg:'e', fx:{dmg:3, block:2} },
  pressure_points: { n:'點穴', en:'Pressure Points', ch:'watcher', c:1, t:'s', r:1, tg:'e', fx:{mark:8} },
  prostrate:       { n:'拜倒', en:'Prostrate', ch:'watcher', c:0, t:'s', r:1, tg:'self', fx:{mantra:2, block:4} },
  protect:         { n:'守護', en:'Protect', ch:'watcher', c:2, t:'s', r:1, tg:'self', fx:{block:12} },
  sash_whip:       { n:'腰帶鞭擊', en:'Sash Whip', ch:'watcher', c:1, t:'a', r:1, tg:'e', fx:{dmg:8, weakIfAttackLast:1} },
  third_eye:       { n:'天眼', en:'Third Eye', ch:'watcher', c:1, t:'s', r:1, tg:'self', fx:{block:7} },
  tranquility:     { n:'寧靜', en:'Tranquility', ch:'watcher', c:1, t:'s', r:1, tg:'self', fx:{stance:'calm', exhaust:1} },
  battle_hymn:     { n:'戰鬥聖歌', en:'Battle Hymn', ch:'watcher', c:1, t:'p', r:2, tg:'self', fx:{battleHymn:1} },
  carve_reality:   { n:'雕刻現實', en:'Carve Reality', ch:'watcher', c:1, t:'a', r:2, tg:'e', fx:{dmg:6, smite:1} },
  conclude:        { n:'終結', en:'Conclude', ch:'watcher', c:1, t:'a', r:2, tg:'all', fx:{dmg:12, aoe:1, endTurn:1} },
  empty_mind:      { n:'空靈之心', en:'Empty Mind', ch:'watcher', c:1, t:'s', r:2, tg:'self', fx:{draw:2, exitStance:1} },
  fear_no_evil:    { n:'無畏邪惡', en:'Fear No Evil', ch:'watcher', c:1, t:'a', r:2, tg:'e', fx:{dmg:8, calmIfAttacking:1} },
  foresight:       { n:'預見', en:'Foresight', ch:'watcher', c:1, t:'p', r:2, tg:'self', fx:{foresight:3} },
  indignation:     { n:'義憤', en:'Indignation', ch:'watcher', c:1, t:'s', r:2, tg:'all', fx:{indignation:3} },
  inner_peace:     { n:'內心平靜', en:'Inner Peace', ch:'watcher', c:1, t:'s', r:2, tg:'self', fx:{innerPeace:3} },
  like_water:      { n:'上善若水', en:'Like Water', ch:'watcher', c:1, t:'p', r:2, tg:'self', fx:{likeWater:5} },
  mental_fortress: { n:'心靈堡壘', en:'Mental Fortress', ch:'watcher', c:1, t:'p', r:2, tg:'self', fx:{mentalFortress:4} },
  nirvana:         { n:'涅槃', en:'Nirvana', ch:'watcher', c:1, t:'p', r:2, tg:'self', fx:{nirvana:3} },
  perseverance:    { n:'堅持不懈', en:'Perseverance', ch:'watcher', c:1, t:'s', r:2, tg:'self', fx:{block:5, persevGrow:2} },
  pray:            { n:'祈禱', en:'Pray', ch:'watcher', c:1, t:'s', r:2, tg:'self', fx:{mantra:3} },
  reach_heaven:    { n:'飛升', en:'Reach Heaven', ch:'watcher', c:2, t:'a', r:2, tg:'e', fx:{dmg:10, throughViolence:1} },
  rushdown:        { n:'速攻', en:'Rushdown', ch:'watcher', c:1, t:'p', r:2, tg:'self', fx:{rushdown:2} },
  sands_of_time:   { n:'時間之沙', en:'Sands of Time', ch:'watcher', c:4, t:'a', r:2, tg:'e', fx:{dmg:20, sandsCostDown:1} },
  signature_move:  { n:'絕招', en:'Signature Move', ch:'watcher', c:2, t:'a', r:2, tg:'e', fx:{dmg:30, needOnlyAttack:1} },
  simmering_fury:  { n:'醞釀怒火', en:'Simmering Fury', ch:'watcher', c:1, t:'s', r:2, tg:'self', fx:{simmeringFury:1} },
  swivel:          { n:'迴身', en:'Swivel', ch:'watcher', c:2, t:'s', r:2, tg:'self', fx:{block:8, freeAttack:1} },
  talk_to_the_hand:{ n:'格擋之手', en:'Talk to the Hand', ch:'watcher', c:1, t:'a', r:2, tg:'e', fx:{dmg:5, talkHand:2, exhaust:1} },
  tantrum:         { n:'發怒', en:'Tantrum', ch:'watcher', c:1, t:'a', r:2, tg:'e', fx:{dmg:3, hits:3, stance:'wrath'} },
  wallop:          { n:'重擊', en:'Wallop', ch:'watcher', c:2, t:'a', r:2, tg:'e', fx:{dmg:9, wallop:1} },
  weave:           { n:'紡織', en:'Weave', ch:'watcher', c:0, t:'a', r:2, tg:'e', fx:{dmg:4} },
  wheel_kick:      { n:'迴旋踢', en:'Wheel Kick', ch:'watcher', c:2, t:'a', r:2, tg:'e', fx:{dmg:15, draw:2} },
  windmill_strike: { n:'風車打擊', en:'Windmill Strike', ch:'watcher', c:2, t:'a', r:2, tg:'e', fx:{dmg:7, windmillGrow:4} },
  worship:         { n:'禮拜', en:'Worship', ch:'watcher', c:2, t:'s', r:2, tg:'self', fx:{mantra:5} },
  wreath_of_flame: { n:'火焰花環', en:'Wreath of Flame', ch:'watcher', c:1, t:'s', r:2, tg:'self', fx:{nextAttackBonus:5} },
  blasphemy:       { n:'褻瀆', en:'Blasphemy', ch:'watcher', c:1, t:'s', r:3, tg:'self', fx:{stance:'divinity', dieNext:1, exhaust:1} },
  brilliance:      { n:'光輝', en:'Brilliance', ch:'watcher', c:1, t:'a', r:3, tg:'e', fx:{dmg:12, dmgPerMantra:1} },
  conjure_blade:   { n:'凝刀', en:'Conjure Blade', ch:'watcher', c:-1, t:'s', r:3, tg:'self', fx:{conjureBlade:1, xCost:1, exhaust:1} },
  deva_form:       { n:'天神形態', en:'Deva Form', ch:'watcher', c:3, t:'p', r:3, tg:'self', fx:{devaForm:1} },
  devotion:        { n:'奉獻精神', en:'Devotion', ch:'watcher', c:1, t:'p', r:3, tg:'self', fx:{devotion:2} },
  judgment:        { n:'審判', en:'Judgment', ch:'watcher', c:1, t:'s', r:3, tg:'e', fx:{judgment:30} },
  lesson_learned:  { n:'吸取教訓', en:'Lesson Learned', ch:'watcher', c:2, t:'a', r:3, tg:'e', fx:{dmg:10, lessonLearned:1, exhaust:1} },
  ragnarok:        { n:'諸神黃昏', en:'Ragnarok', ch:'watcher', c:3, t:'a', r:3, tg:'all', fx:{dmg:5, hits:5, randomTarget:1} },
  scrawl:          { n:'狂書', en:'Scrawl', ch:'watcher', c:1, t:'s', r:3, tg:'self', fx:{drawTo:10, exhaust:1} },
  spirit_shield:   { n:'靈魂之盾', en:'Spirit Shield', ch:'watcher', c:2, t:'s', r:3, tg:'self', fx:{blockPerHandCard:3} },
  vault:           { n:'穿梭時空', en:'Vault', ch:'watcher', c:3, t:'s', r:3, tg:'self', fx:{extraTurn:1, exhaust:1} },

  // ═══ 衍生卡 ═══
  shiv:            { n:'小刀', en:'Shiv', c:0, t:'a', r:0, tg:'e', fx:{dmg:4, exhaust:1}, derived:1 },
  smite_card:      { n:'懲擊', en:'Smite', c:1, t:'a', r:0, tg:'e', fx:{dmg:12, exhaust:1}, derived:1 },
};

// ── 遺物 ──────────────────────────────────────────────
const RELICS = {
  spire_core:      { n:'尖塔核心', icon:'🔆', desc:'每回合能量 +2（隨幕數成長）' },
  violet_lotus:    { n:'紫蓮', icon:'🪷', desc:'離開平靜姿態時額外 +1 能量' },
  third_eye_relic: { n:'天眼冥想', icon:'👁️', desc:'每回合開始獲得 4 真言（集滿 10 進入神聖姿態）' },
  burning_blood:   { n:'燃燒之血', icon:'🩸', desc:'戰鬥結束回復 6 HP' },
  ring_snake:      { n:'蛇之戒指', icon:'🐍', desc:'開場多抽 2 張牌' },
  cracked_core:    { n:'破裂核心', icon:'💠', desc:'開場充能 1 個雷電球' },
  pure_water:      { n:'純淨之水', icon:'💧', desc:'開場加入 1 張懲擊' },
  akabeko:         { n:'紅牛玩偶', icon:'🐮', desc:'每場戰鬥第一次攻擊 +8 傷害' },
  anchor:          { n:'船錨', icon:'⚓', desc:'第一回合獲得 10 格擋' },
  bag_of_marbles:  { n:'彈珠袋', icon:'🔮', desc:'開戰全體敵人易傷 1' },
  bag_of_prep:     { n:'準備背包', icon:'🎒', desc:'開場多抽 2 張牌' },
  blood_vial:      { n:'血瓶', icon:'🧪', desc:'開戰回復 2 HP' },
  bronze_scales:   { n:'青銅鱗片', icon:'🐉', desc:'受到攻擊時反彈 3 傷害' },
  centennial_puzzle:{ n:'百年拼圖', icon:'🧩', desc:'每場首次失去 HP 時抽 3 張' },
  happy_flower:    { n:'快樂花', icon:'🌼', desc:'每 3 回合獲得 1 能量' },
  lantern:         { n:'燈籠', icon:'🏮', desc:'第一回合 +1 能量' },
  nunchaku:        { n:'雙截棍', icon:'🥢', desc:'每打出 10 張攻擊牌 +1 能量' },
  oddly_smooth:    { n:'光滑的石頭', icon:'🪨', desc:'開戰獲得 1 敏捷' },
  orichalcum:      { n:'奧利哈鋼', icon:'🛡️', desc:'回合結束無格擋時 +6 格擋' },
  pen_nib:         { n:'鋼筆尖', icon:'🖋️', desc:'每 10 次攻擊，下次傷害翻倍' },
  vajra:           { n:'金剛杵', icon:'⚡', desc:'開戰獲得 1 力量' },
  kunai:           { n:'苦無', icon:'🗡️', desc:'每回合打 3 張攻擊 +1 敏捷' },
  shuriken:        { n:'手裏劍', icon:'✴️', desc:'每回合打 3 張攻擊 +1 力量' },
  ornamental_fan:  { n:'裝飾摺扇', icon:'🪭', desc:'每回合打 3 張攻擊 +4 格擋' },
  meat_on_bone:    { n:'帶肉的骨頭', icon:'🍖', desc:'戰後 HP 低於一半回復 12' },
  gremlin_horn:    { n:'地精之角', icon:'📯', desc:'敵人死亡時 +1 能量抽 1 張' },
  horn_cleat:      { n:'號角栓', icon:'🥌', desc:'第 2 回合獲得 14 格擋' },
  ice_cream:       { n:'冰淇淋', icon:'🍦', desc:'能量不再於回合結束時消失' },
  torii:           { n:'鳥居', icon:'⛩️', desc:'受到 ≤5 的攻擊傷害減為 1' },
  tungsten_rod:    { n:'鎢棒', icon:'🔩', desc:'受到的 HP 損失 -1' },
  champion_belt:   { n:'冠軍腰帶', icon:'🏆', desc:'施加易傷時附帶虛弱 1' },
  paper_phrog:     { n:'紙蛙', icon:'🐸', desc:'易傷敵人受傷 75%（原 50%）' },
  self_forming_clay:{ n:'自塑黏土', icon:'🏺', desc:'失去 HP 後下回合 +3 格擋' },
};
const RELIC_POOL = Object.keys(RELICS).filter(k => !['spire_core','violet_lotus','third_eye_relic','burning_blood','ring_snake','cracked_core','pure_water'].includes(k));

// ── 藥水 ──────────────────────────────────────────────
const POTIONS = {
  fire:      { n:'火焰藥水', icon:'🧨', fx:{dmg:20}, tg:'e', desc:'對單體造成 20 傷害' },
  block:     { n:'格擋藥水', icon:'🛡️', fx:{block:12}, tg:'self', desc:'獲得 12 格擋' },
  strength:  { n:'力量藥水', icon:'💪', fx:{str:2}, tg:'self', desc:'獲得 2 力量' },
  dexterity: { n:'敏捷藥水', icon:'🌀', fx:{dex:2}, tg:'self', desc:'獲得 2 敏捷' },
  energy:    { n:'能量藥水', icon:'⚡', fx:{energy:2}, tg:'self', desc:'獲得 2 能量' },
  swift:     { n:'迅捷藥水', icon:'💨', fx:{draw:3}, tg:'self', desc:'抽 3 張牌' },
  fear:      { n:'恐懼藥水', icon:'😱', fx:{vuln:3}, tg:'e', desc:'單體易傷 3 回合' },
  weakness:  { n:'虛弱藥水', icon:'🦠', fx:{weak:3}, tg:'e', desc:'單體虛弱 3 回合' },
  poison:    { n:'劇毒藥水', icon:'☠️', fx:{poison:6}, tg:'e', desc:'單體中毒 6 層' },
  blood:     { n:'鮮血藥水', icon:'🩸', fx:{healPct:0.2}, tg:'self', desc:'回復 20% 最大生命' },
  explosive: { n:'爆炸藥水', icon:'💥', fx:{dmg:10, aoe:1}, tg:'all', desc:'對全體造成 10 傷害' },
  ancient:   { n:'遠古藥水', icon:'🏺', fx:{heal:15}, tg:'self', desc:'回復 15 HP' },
};

// ── 怪物（Act 1）──────────────────────────────────────
// intents: 依序循環或加權隨機；atk=攻擊 block=格擋 buff=增益 debuff=減益
const MONSTERS = {
  cultist:    { n:'邪教徒', hp:[48,54], emoji:'🦜', w:70,
                ai:'seq', intents:[{t:'buff', str:3, label:'儀式'},{t:'atk', dmg:6, loop:1}] },
  jaw_worm:   { n:'顎蟲', hp:[40,44], emoji:'🐛', w:66,
                ai:'rand', intents:[{t:'atk', dmg:11, w:45},{t:'buff', str:3, block:6, w:30},{t:'atk', dmg:7, block:5, w:25}] },
  louse_red:  { n:'紅蝨蟲', hp:[10,15], emoji:'🪳', w:44,
                ai:'rand', intents:[{t:'atk', dmg:6, w:75},{t:'buff', str:3, w:25}] },
  louse_green:{ n:'綠蝨蟲', hp:[11,17], emoji:'🦗', w:44,
                ai:'rand', intents:[{t:'atk', dmg:6, w:75},{t:'debuff', weak:2, w:25}] },
  acid_slime: { n:'酸液史萊姆', hp:[28,32], emoji:'🟢', w:56,
                ai:'rand', intents:[{t:'atk', dmg:10, w:40},{t:'atk', dmg:7, weak:1, w:30},{t:'debuff', weak:1, w:30}] },
  spike_slime:{ n:'尖刺史萊姆', hp:[28,32], emoji:'🟣', w:56,
                ai:'rand', intents:[{t:'atk', dmg:8, w:60},{t:'debuff', frail:1, w:40}] },
  gremlin_mad:{ n:'瘋狂地精', hp:[20,24], emoji:'👺', w:46,
                ai:'seq', intents:[{t:'atk', dmg:4, loop:1}] },
  gremlin_fat:{ n:'肥胖地精', hp:[13,17], emoji:'🧌', w:46,
                ai:'seq', intents:[{t:'atk', dmg:4, weak:1, loop:1}] },
  gremlin_shield:{ n:'盾牌地精', hp:[12,15], emoji:'🛡️', w:46,
                ai:'seq', intents:[{t:'block', block:7, loop:1}] },
  slaver_blue:{ n:'藍奴隸販子', hp:[46,50], emoji:'🔱', w:60,
                ai:'rand', intents:[{t:'atk', dmg:12, w:60},{t:'debuff', weak:2, w:40}] },
  fungi_beast:{ n:'真菌獸', hp:[22,28], emoji:'🍄', w:50,
                ai:'rand', intents:[{t:'atk', dmg:6, w:60},{t:'buff', str:3, w:40}] },
  looter:     { n:'掠奪者', hp:[44,48], emoji:'🦝', w:56,
                ai:'seq', intents:[{t:'atk', dmg:10},{t:'atk', dmg:10},{t:'block', block:6},{t:'atk', dmg:12, loop:1}] },
  // 精英
  gremlin_nob:{ n:'地精大王', hp:[82,86], emoji:'👹', w:90, elite:1,
                ai:'seq', intents:[{t:'buff', str:2, label:'咆哮'},{t:'atk', dmg:12},{t:'atk', dmg:6, vuln:2},{t:'atk', dmg:12, loop:2}] },
  lagavulin:  { n:'拉加維林', hp:[109,111], emoji:'🦞', w:100, elite:1,
                ai:'seq', intents:[{t:'block', block:8, label:'沉睡'},{t:'block', block:8, label:'沉睡'},{t:'atk', dmg:16},{t:'atk', dmg:16},{t:'debuff', strDown:1, dexDown:1, loop:2}] },
  sentry:     { n:'哨衛', hp:[38,42], emoji:'🗿', w:64, elite:1,
                ai:'seq', intents:[{t:'atk', dmg:8},{t:'debuff', weak:1, loop:1}] },
  // Boss
  slime_boss: { n:'史萊姆王', hp:[140,140], emoji:'👑', w:130, boss:1,
                ai:'seq', intents:[{t:'debuff', weak:2, label:'黏液噴吐'},{t:'block', block:9, label:'凝聚'},{t:'atk', dmg:32, label:'重壓'},{t:'atk', dmg:10, loop:0}] },
  guardian:   { n:'守護者', hp:[240,240], emoji:'🤖', w:150, boss:1,
                ai:'seq', intents:[{t:'atk', dmg:32, label:'旋轉粉碎'},{t:'block', block:9},{t:'atk', dmg:9, hits:2},{t:'atk', dmg:10, block:9, loop:0}] },
  hexaghost:  { n:'六火亡魂', hp:[250,250], emoji:'👻', w:150, boss:1,
                ai:'seq', intents:[{t:'buff', str:2, label:'點燃'},{t:'atk', dmg:6, hits:2},{t:'atk', dmg:5, hits:3, label:'地獄之火'},{t:'block', block:12},{t:'atk', dmg:18, label:'烈焰噴射', loop:1}] },
};

// ── Act 2 怪物 ──
Object.assign(MONSTERS, {
  chosen:     { n:'天選者', hp:[95,99], emoji:'🧙', w:70,
                ai:'seq', intents:[{t:'debuff', weak:2, label:'咒術'},{t:'atk', dmg:18},{t:'atk', dmg:5, weak:1, loop:1}] },
  byrd:       { n:'鳥人', hp:[25,31], emoji:'🐦', w:46,
                ai:'rand', intents:[{t:'atk', dmg:1, hits:5, w:50},{t:'atk', dmg:12, w:30},{t:'buff', str:1, w:20}] },
  snake_plant:{ n:'蛇草', hp:[75,79], emoji:'🪴', w:64,
                ai:'rand', intents:[{t:'atk', dmg:7, hits:3, w:65},{t:'debuff', frail:2, w:35}] },
  snecko:     { n:'幻蛇', hp:[114,120], emoji:'🐍', w:80,
                ai:'seq', intents:[{t:'debuff', weak:2, label:'凝視'},{t:'atk', dmg:15},{t:'atk', dmg:25, label:'吞咬', loop:1}] },
  shelled_parasite:{ n:'帶殼寄生蟲', hp:[68,72], emoji:'🐚', w:60,
                ai:'rand', intents:[{t:'atk', dmg:6, hits:2, w:40},{t:'atk', dmg:10, w:35},{t:'block', block:8, w:25}] },
  mugger:     { n:'搶匪', hp:[48,52], emoji:'🦹', w:56,
                ai:'seq', intents:[{t:'atk', dmg:10},{t:'atk', dmg:10},{t:'block', block:11},{t:'atk', dmg:16, loop:0}] },
  centurion:  { n:'百夫長', hp:[76,80], emoji:'💂', w:62,
                ai:'rand', intents:[{t:'atk', dmg:12, w:55},{t:'atk', dmg:6, hits:3, w:45}] },
  mystic:     { n:'秘術師', hp:[48,56], emoji:'🧝', w:54,
                ai:'rand', intents:[{t:'buff', str:2, block:8, w:40, label:'聖歌'},{t:'atk', dmg:8, frail:1, w:60}] },
  gremlin_leader:{ n:'地精首領', hp:[140,148], emoji:'👺', w:95, elite:1,
                ai:'seq', intents:[{t:'buff', str:3, block:6, label:'鼓舞'},{t:'atk', dmg:6, hits:3},{t:'atk', dmg:6, hits:3, loop:1}] },
  book_of_stabbing:{ n:'穿刺之書', hp:[160,164], emoji:'📕', w:90, elite:1,
                ai:'rand', intents:[{t:'atk', dmg:6, hits:4, w:70},{t:'atk', dmg:21, w:30}] },
  slaver_red: { n:'紅奴隸販子', hp:[46,50], emoji:'🔴', w:58, elite:1,
                ai:'seq', intents:[{t:'atk', dmg:13},{t:'debuff', weak:2, label:'纏繞'},{t:'atk', dmg:8, vuln:1, loop:0}] },
  the_champ:  { n:'冠軍', hp:[420,420], emoji:'🏆', w:150, boss:1,
                ai:'seq', intents:[{t:'block', block:15, str:2, label:'防禦架勢'},{t:'atk', dmg:12, frail:1, label:'掌摑'},{t:'atk', dmg:16},{t:'buff', str:3, label:'怒火'},{t:'atk', dmg:10, hits:2, label:'處決', loop:1}] },
  bronze_automaton:{ n:'青銅機械人', hp:[300,300], emoji:'🗿', w:150, boss:1,
                ai:'seq', intents:[{t:'buff', str:3, block:9, label:'增幅'},{t:'atk', dmg:7, hits:2, label:'連枷'},{t:'atk', dmg:7, hits:2},{t:'atk', dmg:45, label:'超級光束', loop:0}] },
  the_collector:{ n:'收藏家', hp:[282,282], emoji:'👁️', w:145, boss:1,
                ai:'seq', intents:[{t:'debuff', weak:3, vuln:3, label:'超級詛咒'},{t:'atk', dmg:21, label:'火球'},{t:'buff', str:3, block:15},{t:'atk', dmg:21, label:'火球', loop:1}] },
});

// ── Act 3 怪物 ──
Object.assign(MONSTERS, {
  darkling:   { n:'黑暗傀儡', hp:[48,56], emoji:'🌚', w:56,
                ai:'rand', intents:[{t:'atk', dmg:9, w:60},{t:'buff', str:2, block:6, w:40}] },
  orb_walker: { n:'球行者', hp:[90,96], emoji:'🔮', w:70,
                ai:'rand', intents:[{t:'atk', dmg:10, w:55},{t:'atk', dmg:15, w:45}] },
  spire_growth:{ n:'尖塔增生', hp:[170,170], emoji:'🌵', w:85,
                ai:'rand', intents:[{t:'atk', dmg:16, w:55},{t:'atk', dmg:22, w:30},{t:'debuff', weak:2, label:'纏縛', w:15}] },
  maw:        { n:'血盆大口', hp:[230,230], emoji:'👄', w:110,
                ai:'seq', intents:[{t:'debuff', weak:3, label:'咆哮'},{t:'buff', str:5, label:'流涎'},{t:'atk', dmg:25, label:'猛擊'},{t:'atk', dmg:5, hits:3, loop:2}] },
  writhing_mass:{ n:'蠕動之塊', hp:[160,160], emoji:'🫠', w:90,
                ai:'rand', intents:[{t:'atk', dmg:15, block:12, w:35},{t:'atk', dmg:10, weak:1, w:30},{t:'atk', dmg:32, w:20},{t:'block', block:16, w:15}] },
  transient:  { n:'過客', hp:[999,999], emoji:'💨', w:80,
                ai:'seq', intents:[{t:'atk', dmg:30},{t:'atk', dmg:40},{t:'atk', dmg:50},{t:'atk', dmg:60, loop:3}] },
  giant_head: { n:'巨首', hp:[500,500], emoji:'🗣️', w:140, elite:1,
                ai:'seq', intents:[{t:'debuff', weak:1, label:'凝視'},{t:'atk', dmg:13},{t:'debuff', weak:1},{t:'atk', dmg:13},{t:'atk', dmg:40, label:'時候到了', loop:4}] },
  nemesis:    { n:'復仇女神', hp:[185,185], emoji:'💀', w:100, elite:1, intangibleCycle:1,
                ai:'rand', intents:[{t:'atk', dmg:45, w:30, label:'鐮刀'},{t:'atk', dmg:6, hits:3, w:45},{t:'debuff', weak:2, w:25, label:'烈焰'}] },
  reptomancer:{ n:'馭蛇師', hp:[190,200], emoji:'🐲', w:100, elite:1,
                ai:'rand', intents:[{t:'atk', dmg:13, hits:2, w:55, label:'蛇擊'},{t:'atk', dmg:30, w:25, label:'大蛇噬咬'},{t:'buff', str:2, block:10, w:20}] },
  awakened_one:{ n:'覺醒者', hp:[300,300], emoji:'🕊️', w:150, boss:1, rebirth:1,
                ai:'seq', intents:[{t:'buff', str:2, label:'好奇'},{t:'atk', dmg:20, label:'斬擊'},{t:'atk', dmg:6, hits:4, label:'靈魂打擊'},{t:'atk', dmg:20, loop:1}] },
  time_eater: { n:'時間吞噬者', hp:[456,456], emoji:'⏳', w:155, boss:1,
                ai:'seq', intents:[{t:'atk', dmg:7, hits:3, label:'迴響'},{t:'atk', dmg:26, label:'頭槌'},{t:'block', block:20, str:2, label:'漣漪'},{t:'atk', dmg:7, hits:3, loop:0}] },
  donu:       { n:'多努', hp:[250,250], emoji:'🔷', w:120, boss:1,
                ai:'seq', intents:[{t:'buff', str:3, label:'力量法陣'},{t:'atk', dmg:10, hits:2, label:'光束', loop:0}] },
  deca:       { n:'德卡', hp:[250,250], emoji:'🔶', w:120, boss:1,
                ai:'seq', intents:[{t:'block', block:16, label:'守護法陣'},{t:'atk', dmg:10, hits:2, label:'光束', loop:0}] },
});

const ENCOUNTERS = {
  1: {
    easy:  [['cultist'],['jaw_worm'],['louse_red','louse_green'],['acid_slime','spike_slime']],
    mid:   [['slaver_blue'],['looter'],['fungi_beast','fungi_beast'],['gremlin_mad','gremlin_fat','gremlin_shield'],['acid_slime','louse_red','louse_green']],
    elite: [['gremlin_nob'],['lagavulin'],['sentry','sentry','sentry']],
    boss:  [['slime_boss'],['guardian'],['hexaghost']],
  },
  2: {
    easy:  [['byrd','byrd'],['mugger'],['shelled_parasite'],['chosen']],
    mid:   [['chosen','byrd'],['snake_plant'],['snecko'],['centurion','mystic'],['mugger','shelled_parasite']],
    elite: [['gremlin_leader'],['book_of_stabbing'],['slaver_red','slaver_blue']],
    boss:  [['the_champ'],['bronze_automaton'],['the_collector']],
  },
  3: {
    easy:  [['darkling','darkling'],['orb_walker'],['spire_growth']],
    mid:   [['darkling','darkling','darkling'],['maw'],['writhing_mass'],['orb_walker','orb_walker'],['jaw_worm','jaw_worm','jaw_worm']],
    elite: [['giant_head'],['nemesis'],['reptomancer']],
    boss:  [['awakened_one'],['time_eater'],['donu','deca']],
  },
};
